Related to issue #117
kubernetes-sigs/ingress2gateway pull request #132
Opened 2024-02-13 18:31 UTC by Varun1300211

**What type of PR is this?**
This pull request implements IngressClass support for the ingress2gateway project without utilizing annotations on individual Ingress resources.
It retrieves the default IngressClass based on its API group (networking.k8s.io) and a dedicated annotation (ingressclass.kubernetes.io/is-default-class).
If no explicit IngressClass is specified in the Ingress object or via annotation, the default class is used for resource processing.

Add one of the following kinds:
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

*Automatically closes linked issue when PR is merged.
Usage: `Fixes #117'

Please do let me know if it was done in the correct way.

2024-02-13 18:41 UTC, Varun1300211 commented
/easycla

2024-02-13 18:42 UTC, LiorLieberman commented
/ok-to-test

2024-02-13 20:02 UTC, Varun1300211 commented
Done all the changes requested by you @LiorLieberman, please let me know if anything else is required.

2024-02-14 06:07 UTC, levikobi reviewed
Thanks @Varun1300211 and welcome!
I left a few comments regarding some things that need to be taken into account.
If you have any questions or need any help feel free to let us know

2024-02-14 06:07 UTC, levikobi commented on pkg/i2gw/providers/common/utils.go
> +	ingressClasses, err := k8sClientset.NetworkingV1().IngressClasses().List(context.Background(), metav1.ListOptions{})
We support 2 modes for reading resources: from the cluster or a local file.
Here it seems that you're always reading from the cluster. We should come up with a way to take into account the user's choice

2024-02-14 06:07 UTC, levikobi commented on pkg/i2gw/providers/common/utils.go
> +		}
We should probably return an error in this case

2024-02-14 21:13 UTC, Varun1300211 commented
Hi @levikobi, I made the changes suggested by you. Please take a look.

2024-02-18 18:11 UTC, levikobi requested changes
Thanks again @Varun1300211!
I think it may help you to try playing around with the tool for a bit and see the different options it provides. Afterwards maybe try to compile your version and see what changes/breaks.

This new addition needs to take into account different options the user may pass.

2024-02-18 18:11 UTC, levikobi commented on pkg/i2gw/providers/common/utils.go
> +	}
Maybe I missed something but it seems like you're always sending an empty slice of data

2024-02-18 18:11 UTC, levikobi commented on pkg/i2gw/providers/common/utils.go
> +}
This init function will always try to create a k8s client, even if the user doesn't have a cluster and want to convert some local file.

You'll need to pass the user's choice of where he wants to read resources from (cluster or file) and the k8s client, which was initialized in the i2gw package.

2024-03-02 16:54 UTC, LiorLieberman commented
@Varun1300211 just checking in, do you need help with moving this forward?

2024-03-02 16:54 UTC, LiorLieberman commented
@Varun1300211 Just checking in, please let us know if you need any help with moving this forward

2024-04-03 09:58 UTC, LiorLieberman commented
@Varun1300211 a friendly ping, are you still planning to work on this?

2024-05-07 06:26 UTC, closed without merging