feat: bump ReferenceGrant to v1beta1
kubernetes-sigs/ingress2gateway pull request #142
Opened 2024-03-08 12:53 UTC by YTGhost

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
`ReferenceGrant` has been promoted to `v1beta1` but we are still using the `alpha` version. We should bump the API.

**Which issue(s) this PR fixes**:

Fixes #140 

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-03-08 12:55 UTC, YTGhost commented
Hi @mlavacca @LiorLieberman PTAL

2024-03-10 18:38 UTC, levikobi reviewed
Thanks @YTGhost!
/ok-to-test

2024-03-11 10:36 UTC, mlavacca requested changes
Thanks for this PR, @YTGhost! In addition to what's in this PR, I found some more `gatewayv1alpha1.ReferenceGrant` references that need to be changed as well:

https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/common/converter.go#L94-L98

https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/istio/converter_test.go#L1593-L1619

https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/istio/converter.go#L978-L1026

2024-03-11 13:16 UTC, YTGhost commented
> Thanks for this PR, @YTGhost! In addition to what's in this PR, I found some more `gatewayv1alpha1.ReferenceGrant` references that need to be changed as well:
> 
> https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/common/converter.go#L94-L98
> 
> https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/istio/converter_test.go#L1593-L1619
> 
> https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/istio/converter.go#L978-L1026

Hi, @mlavacca , thank you for your review! I have also checked this PR again and found some other areas that need modification. I believe this PR should now be complete.

2024-03-27 11:54 UTC, LiorLieberman commented
/cc @mlavacca 
Can you take another look?

2024-03-27 11:54 UTC, LiorLieberman commented
@YTGhost can you add release note?

2024-03-27 12:07 UTC, YTGhost commented
> @YTGhost can you add release note?

Okay

2024-03-28 09:27 UTC, mlavacca approved these changes
Thanks @YTGhost!
/lgtm

2024-03-28 12:02 UTC, LiorLieberman commented
/approve

2024-03-28 15:16 UTC, YTGhost commented
@LiorLieberman  Sorry for the missing modification in the last `gatewayv1alpha2.ReferenceGrant` in `pkg/i2gw/ingress2gateway.go`. PTAL.

2024-03-29 10:08 UTC, mlavacca commented
/lgtm

2024-03-29 10:11 UTC, merged