added ingresses-only flag
kubernetes-sigs/ingress2gateway pull request #69
Opened 2023-09-28 07:23 UTC by camperjett

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
this adds a new flag `ingresses-only` to scope the tool to only convert resources without looking for providers CRDs

**Which issue(s) this PR fixes**:
Fixes #67 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @LiorLieberman

2023-09-28 18:19 UTC, levikobi requested changes
Thank you for your contribution @camperjett!

Removing the gateway objects is not exactly what we had in mind here. What we intended to do was to not translate provider-specific functionality by not running provider converters.
Maybe you can take a look at https://github.com/kubernetes-sigs/ingress2gateway#usage for some reference.

Let me know if you have any questions.

2023-10-01 06:52 UTC, camperjett commented
Okay. This is similar to passing empty list of providers in function `i2gw.ToGatewayAPIResources(...)` right? Should I do that?

2023-10-02 17:52 UTC, levikobi commented
> Okay. This is similar to passing empty list of providers in function `i2gw.ToGatewayAPIResources(...)` right? Should I do that? (In file cmd/print.go, Inside function `PrintGatewaysAndHTTPRoutes(...)`)

Yes that seems about right

One more thing that comes to mind, this flag should probably be mutually exclusive with the providers flag

2023-10-02 17:53 UTC, levikobi commented on cmd/print.go
> +	cmd.Flags().BoolVar(&pr.ingressesOnly, "ingresses-only", false, "If present, the tool will only print the converted Ingresses.")
Should be mutually exclusive with the providers flag

2023-10-07 10:51 UTC, closed without merging

2023-10-07 11:42 UTC, camperjett commented
PTAL at 
#71